openapi: 3.0.3
info:
  title: Calendar API
  version: 1.0.0
  description: API do zarządzania kalendarzami i wydarzeniami

paths:
  /api/calendars:
    $ref: './paths/calendar/calendars.yaml'

  /api/calendars/{calendarId}:
    $ref: './paths/calendar/calendars-by-id.yaml'

  /api/events:
    $ref: './paths/event/events.yaml'

  /api/events/search:
    $ref: './paths/event/events-search.yaml'

  /api/events/{eventId}/attendees:
    $ref: './paths/event/events-attendees-by-event-id.yaml'

  /api/events/{eventId}/response:
    $ref: './paths/event/events-response.yaml'

  /api/events/{eventId}:
    $ref: './paths/event/events-by-id.yaml'

  /api/events/{eventId}/attendees/{attendeeId}:
    $ref: './paths/event/event-attendees-by-attendee-id.yaml'

components:
  schemas:
    AttendeeDto:
      $ref: './components/schemas/AttendeeDto.yaml'
    Attendee:
      $ref: './components/schemas/Attendee.yaml'
    CalendarDto:
      $ref: './components/schemas/CalendarDto.yaml'
    Calendar:
      $ref: './components/schemas/Calendar.yaml'
    EventDto:
      $ref: './components/schemas/EventDto.yaml'
    Event:
      $ref: './components/schemas/Event.yaml'
    FilterRequest:
      $ref: './components/schemas/FilterRequest.yaml'
    PageRequest:
      $ref: './components/schemas/PageRequest.yaml'
    SearchFilter:
      $ref: './components/schemas/SearchFilter.yaml'
    SortRequest:
      $ref: './components/schemas/SortRequest.yaml'
    ResponseStatus:
      $ref: './components/schemas/enums/ResponseStatus.yaml'
    EventStatus:
      $ref: './components/schemas/enums/EventStatus.yaml'